POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVra2FpIiwiaWQiOiI1ZWEwMmQyNjNlYTc2ODM2MzAxNmVkMzYiLCJpYXQiOjE1ODc1NzIzNDN9.uCLd1BcvNChobZKbFjoW3Mw9Jn219lxopGktVffvwHE

{
	"url": "fake.one/ex4/20/1",
	"title": "sent from a registered user 2"
}